name: release
on:
  workflow_run:
    workflows: ['tests']
    types:
      - completed
permissions:
  contents: write
  id-token: write
  pull-requests: write

jobs:
  publish:
    runs-on: ubuntu-latest
    if: ${{ github.ref == 'refs/heads/main' && github.event.workflow_run.conclusion == 'success' }}
    steps:
      - uses: actions/checkout@v6
      - uses: actions/setup-node@v6
        with:
          node-version: '24.x'
      - run: corepack enable
      - run: yarn install --immutable
      - run: yarn semantic-release
        env:
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
